# Generated by Django 5.1.5 on 2025-03-10 15:07

import author.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('author_type', models.CharField(choices=[('INDIVIDUAL', 'Физическое лицо'), ('INDIVIDUAL_ENTREPRENEUR', 'Индивидуальный предприниматель'), ('ORGANIZATION', 'Организация'), ('SCHOOL', 'Школа')], default='INDIVIDUAL', max_length=150, verbose_name='Тип автора')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержденный автор?')),
                ('title', models.CharField(help_text='Название организации автора', max_length=255, verbose_name='Название')),
                ('full_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полное название')),
                ('alias', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Короткое название')),
                ('prepositional_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название в предложном падеже')),
                ('genitive_title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название в родительском падеже')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=author.utils.logos_document_path, verbose_name='Логотип')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('legal_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес регистрации')),
                ('education_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип образования')),
                ('is_premium_partner', models.BooleanField(default=False, verbose_name='Премиум партнёр?')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
            bases=('userauth.customuser',),
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=150, unique=True, verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Тип Документа',
                'verbose_name_plural': 'Типы Документов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=author.utils.profile_document_path, verbose_name='Документ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='author.author', verbose_name='Автор')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('INDIVIDUAL', 'Физическое лицо'), ('INDIVIDUAL_ENTREPRENEUR', 'Индивидуальный предприниматель'), ('ORGANIZATION', 'Организация'), ('SCHOOL', 'Школа')], default='INDIVIDUAL', max_length=150, verbose_name='Тип автора')),
                ('document_types', models.ManyToManyField(to='author.documenttype', verbose_name='Типы документов')),
            ],
            options={
                'verbose_name': 'Обязательные Документ',
                'verbose_name_plural': 'Обязательные Документы',
            },
        ),
    ]
