# Generated by Django 5.1.5 on 2025-03-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Физическое лицо'), ('INDIVIDUAL_ENTREPRENEUR', 'Индивидуальный предприниматель'), ('ORGANIZATION', 'Организация')], default='INDIVIDUAL', max_length=150, verbose_name='Тип автора'),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='author_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Физическое лицо'), ('INDIVIDUAL_ENTREPRENEUR', 'Индивидуальный предприниматель'), ('ORGANIZATION', 'Организация')], default='INDIVIDUAL', max_length=150, verbose_name='Тип автора'),
        ),
        migrations.CreateModel(
            name='FIZAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('fio_short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое ФИО')),
                ('passport_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер паспорта')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан паспорт')),
                ('passport_code_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код подразделения')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактный телефон')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('snils', models.CharField(blank=True, max_length=100, null=True, verbose_name='СНИЛС')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('bank_bik', models.CharField(blank=True, max_length=100, null=True, verbose_name='БИК банка')),
                ('bank_ks', models.CharField(blank=True, max_length=100, null=True, verbose_name='КС банка')),
                ('bank_rs', models.CharField(blank=True, max_length=100, null=True, verbose_name='РС банка')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiz_author', to='author.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='FOPAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('fio_short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое ФИО')),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регистрационный номер в реестре')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактный телефон')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('bank_bik', models.CharField(blank=True, max_length=100, null=True, verbose_name='БИК банка')),
                ('bank_ks', models.CharField(blank=True, max_length=100, null=True, verbose_name='КС банка')),
                ('bank_rs', models.CharField(blank=True, max_length=100, null=True, verbose_name='РС банка')),
                ('ogrnip_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРНИП')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fop_author', to='author.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='LLCAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации')),
                ('name_short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название организации')),
                ('director_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя директора')),
                ('director_short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сокращенное имя директора')),
                ('buhgaler_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя бухгалтера')),
                ('buhgaler_short_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сокращенное имя бухгалтера')),
                ('kpp', models.CharField(blank=True, max_length=100, null=True, verbose_name='КПП')),
                ('okpo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКПО')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('oktmo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКТМО')),
                ('ogrn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактный телефон')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('bank_bik', models.CharField(blank=True, max_length=100, null=True, verbose_name='БИК банка')),
                ('bank_ks', models.CharField(blank=True, max_length=100, null=True, verbose_name='КС банка')),
                ('bank_rs', models.CharField(blank=True, max_length=100, null=True, verbose_name='РС банка')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llc_author', to='author.author', verbose_name='Автор')),
            ],
        ),
    ]
