# Generated by Django 5.1.5 on 2025-03-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_author_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizauthor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Рабочая электронная почта'),
        ),
        migrations.AddField(
            model_name='fopauthor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Рабочая электронная почта'),
        ),
        migrations.AddField(
            model_name='llcauthor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта организации'),
        ),
    ]
