# Generated by Django 5.1.5 on 2025-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_fizauthor_email_fopauthor_email_llcauthor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован автор?'),
        ),
    ]
