# Generated by Django 5.1.5 on 2025-03-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Не проверен'), ('ON_VERIFICATION', 'На проверке'), ('VERIFIED', 'Проверен')], default='UNVERIFIED', max_length=150, verbose_name='Статус проверки'),
        ),
    ]
