services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: test_nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./backend/static:/app/static:ro
      - ./backend/media:/app/media:ro
      - ./frontend/dist:/frontend_dist
    networks:
      - backend

  redis:
    image: redis:6
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_test:/data
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: test_vue_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.test
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: test_django_backend
    volumes:
        - ./backend/media:/app/media
        - ./backend/static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.test
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "
      pwd
      echo 'Ожидание БД...' &&
      while ! nc -z database 5432; do sleep 1; done &&
      echo 'БД доступна!' &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      uvicorn core.asgi:application --host 0.0.0.0 --port 8000"
    networks:
      - backend

  database:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env.test
    volumes:
      - db_data_test:/var/lib/postgresql/data
    ports:
      - "54323:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d marketplace_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data_test:
  redis_data_test:

networks:
  backend:
    driver: bridge
