services:
  redis:
    image: redis:6
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: local_vue_frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./frontend/.env
    command: npm run dev --debug
    ports:
      - "5173:5173"
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: local_django_backend
    volumes:
      - ./backend:/app
      - ./backend/static:/backend_static
      - ./backend/media:/backend_media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "
      echo 'Waiting for database...' &&
      while ! nc -z database 5432; do sleep 1; done &&
      echo 'Database is available!' &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      uvicorn core.asgi:application --host 0.0.0.0 --port 8000"
    networks:
      - backend

  database:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  redis_data:

networks:
  backend:
    driver: bridge