# Generated by Django 5.1.5 on 2025-04-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обращения', 'verbose_name_plural': 'Обращения'},
        ),
    ]
