# Generated by Django 5.1.5 on 2025-03-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='author.author')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('partner_card', models.BooleanField(default=False, verbose_name='Есть карта партнёра?')),
                ('license', models.CharField(blank=True, max_length=500, null=True, verbose_name='Лицензия')),
                ('personal_account_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя персонального аккаунта')),
                ('personal_account_site', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Сайт персонального аккаунта')),
                ('leadership', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
            bases=('author.author',),
        ),
        migrations.CreateModel(
            name='OrganizationRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bik', models.CharField(blank=True, help_text='Банковский Идентификационный Код', max_length=255, null=True, verbose_name='БИК')),
                ('inn', models.CharField(blank=True, help_text='Идентификационный Номер Налогоплательщика', max_length=255, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='Код Причины Постановки на учет', max_length=255, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, help_text='Основной Государственный Регистрационный Номер', max_length=255, null=True, verbose_name='ОГРН')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
    ]
