# Generated by Django 5.1.5 on 2025-03-10 15:07

import django.core.validators
import django.db.models.deletion
import tariffs.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='Скидка должна быть в диапазоне от 0 до 100. Пример: 42', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидка')),
                ('percentage', models.PositiveSmallIntegerField(default=0, help_text='Процент должен быть в диапазоне от 0 до 100. Пример: 42', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент с продаж')),
                ('is_show', models.BooleanField(default=True, verbose_name='Показывать?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('duration', models.CharField(choices=[('TIMELESSLY', 'Без срочный'), ('MONTHLY', 'Месячный'), ('YEARLY', 'Годовой')], default='MONTHLY', max_length=10, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='TariffFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tariffs.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Предложение Тарифа',
                'verbose_name_plural': 'Предложения Тарифа',
            },
        ),
        migrations.CreateModel(
            name='UserTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expire', models.DateTimeField(blank=True, null=True, validators=[tariffs.validators.validate_expire_date], verbose_name='Дата окончания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('is_timeless', models.BooleanField(default=False, verbose_name='Без срока окончания?')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tariffs.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Оплаченный Тариф',
                'verbose_name_plural': 'Оплаченные Тарифы',
            },
        ),
    ]
