# Generated by Django 5.1.5 on 2025-04-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionoffices',
            options={'verbose_name': 'Приемная комиссия', 'verbose_name_plural': 'Приемные комиссии'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='directions',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='directionsorganizations',
            options={'verbose_name': 'Направление ВУЗа', 'verbose_name_plural': 'Направления ВУЗов'},
        ),
        migrations.AlterModelOptions(
            name='faculties',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'Форма обучения', 'verbose_name_plural': 'Формы обучения'},
        ),
        migrations.AlterModelOptions(
            name='metros',
            options={'verbose_name': 'Станция метро', 'verbose_name_plural': 'Станции метро'},
        ),
        migrations.AlterModelOptions(
            name='organizationsvuz',
            options={'verbose_name': 'ВУЗ', 'verbose_name_plural': 'ВУЗы'},
        ),
        migrations.AlterModelOptions(
            name='professions',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AlterModelOptions(
            name='professionsorganizations',
            options={'verbose_name': 'Профессия ВУЗа', 'verbose_name_plural': 'Профессии ВУЗов'},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='specialties',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='specialtiesorganizations',
            options={'verbose_name': 'Специальность ВУЗа', 'verbose_name_plural': 'Специальности ВУЗов'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата внешнего обновления'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='is_full_year',
            field=models.BooleanField(verbose_name='Работает весь год'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='longitude_latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='phones',
            field=models.JSONField(blank=True, null=True, verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='post_index',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='schedule',
            field=models.JSONField(blank=True, null=True, verbose_name='Расписание работы'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='admissionoffices',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='calculation_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Расчетные данные по городу'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='city_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип населенного пункта'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='fias_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор ФИАС'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='is_capital',
            field=models.BooleanField(verbose_name='Является столицей'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='kladr_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор КЛАДР'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='longitude_latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name_rp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в родительном падеже'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='ratio_population',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Категория по населению'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phones',
            field=models.TextField(blank=True, null=True, verbose_name='Список телефонов'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='post_index',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='calculation_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Расчетные параметры направления'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код направления'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название направления'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='organization_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='synonym',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Синоним'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='directionsorganizations',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.directions', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='directionsorganizations',
            name='organization_vuz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.organizationsvuz', verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='calculation_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Расчетные параметры факультета'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='longitude_latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='organization_vuz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.organizationsvuz', verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='post_index',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название формы обучения'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='metros',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='metros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metros',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='metros',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='metros',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='metros',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О ВУЗе'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='accreditation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата аккредитации'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='accreditation_number',
            field=models.CharField(blank=True, null=True, verbose_name='Номер аккредитации'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='admission_office',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.admissionoffices', verbose_name='Приемная комиссия'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='calculation_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Расчетные параметры организации'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='confirmed_and_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.contacts', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='delete_reason',
            field=models.CharField(blank=True, null=True, verbose_name='Причина удаления'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='ege_score',
            field=models.CharField(blank=True, null=True, verbose_name='Балл ЕГЭ'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='esi',
            field=models.FloatField(blank=True, null=True, verbose_name='ЕСИ'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='esi24',
            field=models.CharField(blank=True, null=True, verbose_name='ЕСИ24'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='esi_marks',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценки ЕСИ'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата внешнего обновления'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='has_leads',
            field=models.BooleanField(verbose_name='Есть лиды'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='inn',
            field=models.CharField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='is_confirmed',
            field=models.BooleanField(verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='is_departmental',
            field=models.BooleanField(verbose_name='Ведомственный'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='is_hostel',
            field=models.BooleanField(verbose_name='Есть общежитие'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='is_military',
            field=models.BooleanField(verbose_name='Военный'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='is_partner',
            field=models.BooleanField(verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='is_state',
            field=models.BooleanField(verbose_name='Государственный'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='is_top100',
            field=models.BooleanField(verbose_name='Топ 100'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='kpp',
            field=models.CharField(blank=True, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='licence_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата лицензии'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='licence_num',
            field=models.CharField(blank=True, null=True, verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='logo',
            field=models.CharField(blank=True, null=True, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='logo_storage',
            field=models.CharField(blank=True, null=True, verbose_name='Хранилище логотипа'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='longitude_latitude',
            field=models.CharField(blank=True, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.metros', verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='monitoring_code',
            field=models.CharField(blank=True, null=True, verbose_name='Код мониторинга'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='obrnadzor_checked',
            field=models.BooleanField(blank=True, null=True, verbose_name='Проверено Обрнадзором'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='obrnadzor_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название в Обрнадзоре'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='old_names',
            field=models.TextField(blank=True, null=True, verbose_name='Старые названия'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='organization_type',
            field=models.CharField(blank=True, null=True, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='published',
            field=models.BooleanField(verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='short_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='short_seo',
            field=models.CharField(blank=True, null=True, verbose_name='SEO краткое название'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='site',
            field=models.CharField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='sort_for_region',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сортировка для региона'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='sort_for_top',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сортировка для топа'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='sub_type',
            field=models.CharField(blank=True, null=True, verbose_name='Подтип'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.subjects', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='organizationsvuz',
            name='video_link',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='detail_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Детальное изображение'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата внешнего обновления'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='extra_names',
            field=models.JSONField(blank=True, null=True, verbose_name='Основные формы названия профессии'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='full_text',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='organization_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='other_text_1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительный текст 1'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='other_text_2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительный текст 2'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='preview_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Превью изображение'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='published',
            field=models.BooleanField(verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='short_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='professionsorganizations',
            name='organization_vuz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.organizationsvuz', verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='professionsorganizations',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.professions', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='budget_places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество бюджетных мест'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='budget_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проходной балл на бюджет'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='calculation_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Расчетные данные программы'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='commercial_places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество платных мест'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='commercial_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проходной балл на платное'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость обучения'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность обучения в месяцах'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.faculties', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.forms', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='organization_vuz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.organizationsvuz', verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='profile',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Название профиля/направления'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.specialties', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='calculation_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Расчетные параметры специальности'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='code_okso',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код ОКСО'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='code_okso_new',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Новый код ОКСО'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='code_old',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Старый код'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='description_work',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='level_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код уровня'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='specialties',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='specialtiesorganizations',
            name='organization_vuz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.organizationsvuz', verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='specialtiesorganizations',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vuz.specialties', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='fias_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор ФИАС'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='kladr_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор КЛАДР'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name_rp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в родительном падеже'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата обновления'),
        ),
    ]
