# Generated by Django 5.1.5 on 2025-04-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0002_alter_admissionoffices_options_alter_cities_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
    ]
