# Generated by Django 5.1.5 on 2025-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0003_alter_subjects_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип области'),
        ),
    ]
