# Generated by Django 5.1.5 on 2025-04-25 13:09

from django.db import migrations
import os
import json
from pathlib import Path
from datetime import datetime
from django.db import migrations
from django.utils import timezone

def _parse_datetime(date_str):
    if not date_str:
        return None
    try:
        return datetime.fromisoformat(date_str)
    except (ValueError, TypeError):
        return None

def _load_data_for_model(apps, model_name, json_file, relation_fields=None):
    if relation_fields is None:
        relation_fields = {}
        
    model_class = apps.get_model('vuz', model_name)
    base_path = Path(__file__).resolve().parent.parent.parent
    file_path = os.path.join(base_path, "maintenance", "files", "vuz", json_file)
    
    print(f"\tОткрываю файл: {file_path}")
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            json_data = json.load(file)
            
            data = None
            model_name_lower = model_name.lower()
            
            if model_name_lower in json_data:
                data = json_data[model_name_lower]
            elif json_file.split('.')[0] in json_data:
                data = json_data[json_file.split('.')[0]]
            else:
                data = json_data
            
            if isinstance(data, str):
                print(f"\tФайл {file_path} содержит строку вместо JSON-объекта")
                return
            elif not isinstance(data, list):
                if isinstance(data, dict) and not any(isinstance(data[key], dict) for key in data):
                    data = [data]
                else:
                    extracted_data = []
                    for key, value in data.items():
                        if isinstance(value, dict):
                            extracted_data.append(value)
                    if extracted_data:
                        data = extracted_data
                    else:
                        data = [data]
            print(f"\tЗагружено {len(data)} записей из файла {json_file}")
            
    except FileNotFoundError:
        print(f"\tФайл {file_path} не найден")
        return
    except json.JSONDecodeError:
        print(f"\tФайл {file_path} содержит невалидный JSON")
        return

    for idx, item in enumerate(data):
        if idx % 1000 == 0 and idx > 0:
            print(f"\t\tОбработано {idx}/{len(data)} записей...")
        if not isinstance(item, dict):
            print(f"\tПропущена несловарная запись под индексом {idx}")
            continue
            
        item_data = item.copy()
        
        model_fields = [field.name for field in model_class._meta.fields]
        model_field_objects = {field.name: field for field in model_class._meta.fields}
        
        for field in model_class._meta.fields:
            if field.is_relation:
                if field.name not in model_fields:
                    model_fields.append(field.name)
                field_id = f"{field.name}_id"
                if field_id not in model_fields:
                    model_fields.append(field_id)
        
        item_data = {key: value for key, value in item_data.items() if key in model_fields}
        
        if 'phones' in item_data:
            phones_value = item_data['phones']
            if isinstance(phones_value, str):
                if phones_value.startswith('{') and phones_value.endswith('}'):
                    phones_content = phones_value[1:-1]
                    
                    if '"' in phones_content:
                        phones_items = []
                        in_quotes = False
                        current_item = ""
                        
                        for char in phones_content:
                            if char == '"':
                                in_quotes = not in_quotes
                            elif char == ',' and not in_quotes:
                                if current_item:
                                    phones_items.append(current_item.strip('"').strip())
                                    current_item = ""
                            else:
                                current_item += char
                        
                        if current_item:
                            phones_items.append(current_item.strip('"').strip())
                        
                        item_data['phones'] = phones_items
                    else:
                        phones_list = [phone.strip() for phone in phones_content.split(',')]
                        item_data['phones'] = phones_list
                elif phones_value.startswith('[') and phones_value.endswith(']'):
                    try:
                        item_data['phones'] = json.loads(phones_value)
                    except json.JSONDecodeError:
                        pass
        
        for field_name, field_value in list(item_data.items()):
            if field_name in model_field_objects:
                field_obj = model_field_objects[field_name]
                field_type = field_obj.__class__.__name__
                
                if field_type in ['JSONField', 'TextField'] and isinstance(field_value, str):
                    if field_value.startswith('{') and field_value.endswith('}') or \
                       field_value.startswith('[') and field_value.endswith(']'):
                        try:
                            item_data[field_name] = json.loads(field_value)
                        except json.JSONDecodeError:
                            pass
        
        for field in ['created_at', 'updated_at', 'external_updated_at', 'confirmed_and_date', 
                      'licence_date', 'accreditation_date', 'start_date', 'end_date']:
            if field in item_data:
                item_data[field] = _parse_datetime(item_data[field])
        
        for field, (related_model_name, lookup_field) in relation_fields.items():
            if field in item_data and item_data[field]:
                try:
                    related_model = apps.get_model('vuz', related_model_name)
                    related_obj = related_model.objects.get(**{lookup_field: item_data[field]})
                    item_data[field] = related_obj
                except related_model.DoesNotExist:
                    print(f"\t\tСвязанный объект {related_model_name} с {lookup_field}={item_data[field]} не найден (запись {idx})")
                    item_data[field] = None
                except Exception as e:
                    print(f"\t\tОшибка при поиске связанного объекта {related_model_name}: {e} (запись {idx})")
                    item_data[field] = None

        try:
            if 'created_at' in model_fields:
                if 'created_at' not in item_data or item_data['created_at'] is None:
                    item_data['created_at'] = timezone.now()
            if 'updated_at' in model_fields:
                if 'updated_at' not in item_data or item_data['updated_at'] is None:
                    item_data['updated_at'] = timezone.now()
            if 'created_at' in item_data and 'created_at' not in model_fields:
                del item_data['created_at']
            if 'updated_at' in item_data and 'updated_at' not in model_fields:
                del item_data['updated_at']
            
            boolean_fields = [
                'published', 'is_state', 'is_hostel', 'is_military', 'is_departmental', 
                'is_partner', 'has_leads', 'is_confirmed', 'is_top100', 'is_full_year',
                'is_capital', 'obrnadzor_checked'
            ]
            
            for field in boolean_fields:
                if field in model_fields and field in item_data and item_data[field] is None:
                    item_data[field] = False
            
            if 'id' in item_data and item_data['id']:
                filter_params = {'id': item_data['id']}
                if 'type' in item_data and 'source' in item_data:
                    filter_params['type'] = item_data['type']
                    filter_params['source'] = item_data['source']
                
                obj, created = model_class.objects.update_or_create(
                    **filter_params,
                    defaults=item_data
                )
            else:
                obj = model_class.objects.create(**item_data)
                print(f"\t\tСоздан новый объект {model_name} (id={obj.id})")
                
        except Exception as e:
            print(f"\t\tОшибка при обработке записи {item_data}: {str(e)}")
    print(f"\tЗагрузка для модели {model_name} завершена. Всего обработано: {len(data)} записей.")

def load_initial_data(apps, schema_editor):
    model_loaders = {
        'Cities': {
            'file': 'cities.json',
            'relations': {}
        },
        'Metros': {
            'file': 'metros.json',
            'relations': {}
        },
        'Subjects': {
            'file': 'subjects.json',
            'relations': {}
        },
        'Contacts': {
            'file': 'contacts.json',
            'relations': {}
        },
        'AdmissionOffices': {
            'file': 'admission_offices.json',
            'relations': {}
        },
        'OrganizationsVuz': {
            'file': 'organizations_vuz.json',
            'relations': {
                'city': ('Cities', 'id'),
                'subject': ('Subjects', 'id'),
                'metro': ('Metros', 'id'),
                'contact': ('Contacts', 'id'),
                'admission_office': ('AdmissionOffices', 'id')
            }
        },
        'Directions': {
            'file': 'directions.json',
            'relations': {}
        },
        'DirectionsOrganizations': {
            'file': 'directions_organizations.json',
            'relations': {
                'direction': ('Directions', 'id'),
                'organization_vuz': ('OrganizationsVuz', 'id')
            }
        },
        'Faculties': {
            'file': 'faculties.json',
            'relations': {
                'organization_vuz': ('OrganizationsVuz', 'id')
            }
        },
        'Forms': {
            'file': 'forms.json',
            'relations': {}
        },
        'Professions': {
            'file': 'professions.json',
            'relations': {}
        },
        'ProfessionsOrganizations': {
            'file': 'professions_organizations.json',
            'relations': {
                'profession': ('Professions', 'id'),
                'organization_vuz': ('OrganizationsVuz', 'id')
            }
        },
        'Specialties': {
            'file': 'specialties.json',
            'relations': {}
        },
        'SpecialtiesOrganizations': {
            'file': 'specialties_organizations.json',
            'relations': {
                'specialty': ('Specialties', 'id'),
                'organization_vuz': ('OrganizationsVuz', 'id')
            }
        },
        'Programs': {
            'file': 'programs.json',
            'relations': {
                'organization_vuz': ('OrganizationsVuz', 'id'),
                'faculty': ('Faculties', 'id'),
                'specialty': ('Specialties', 'id'),
                'form': ('Forms', 'id')
            }
        }
    }

    print("\n=== НАЧАЛО ЗАГРУЗКИ ВСЕХ ДАННЫХ ===")
    for model_name, loader in model_loaders.items():
        print(f"\nЗагрузка данных для модели {model_name}")
        _load_data_for_model(
            apps,
            model_name,
            loader['file'],
            loader['relations']
        )
    print("\n=== ЗАГРУЗКА ВСЕХ ДАННЫХ ЗАВЕРШЕНА ===")

def reverse_load_initial_data(apps, schema_editor):
    models = [
        'Programs', 'SpecialtiesOrganizations', 'ProfessionsOrganizations',
        'DirectionsOrganizations', 'Faculties', 'OrganizationsVuz',
        'AdmissionOffices', 'Contacts', 'Subjects', 'Metros', 'Cities',
        'Forms', 'Directions', 'Professions', 'Specialties'
    ]
    
    for model_name in reversed(models):
        model = apps.get_model('vuz', model_name)
        model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0004_alter_subjects_subject_type'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_load_initial_data),
    ]
