# Generated by Django 5.1.5 on 2025-05-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vuz', '0008_clean_faculty_names'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forms',
            name='forms_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='programs',
            name='programs_form_idx',
        ),
        migrations.RemoveIndex(
            model_name='programs',
            name='programs_faculty_idx',
        ),
        migrations.RemoveIndex(
            model_name='programs',
            name='programs_specialty_idx',
        ),
    ]
