# Generated by Django 5.1.5 on 2025-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('html', models.TextField(blank=True, null=True, verbose_name='HTML формат')),
                ('notification_type', models.CharField(choices=[('Payment is expected', 'Ожидается оплата'), ('Update of the terms', 'Обновление условий'), ('Confirmation of participation', 'Подтверждение участия'), ('A reminder about meeting', 'Напоминание о встрече'), ('Schedule change', 'Изменения расписания'), ('Successful registration', 'Успешная регистрация'), ('Refund approved', 'Возврат оформлен')], max_length=255, verbose_name='Тип')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
