# Generated by Django 5.1.5 on 2025-03-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Payment is expected', 'Ожидается оплата'), ('Payment successful', 'Оплата прошла успешно'), ('Payment failed', 'Оплата не прошла'), ('Update of the terms', 'Обновление условий'), ('Confirmation of participation', 'Подтверждение участия'), ('A reminder about meeting', 'Напоминание о встрече'), ('Schedule change', 'Изменения расписания'), ('Successful registration', 'Успешная регистрация'), ('Refund approved', 'Возврат оформлен')], max_length=255, verbose_name='Тип'),
        ),
    ]
