# Generated by Django 5.1.5 on 2025-03-10 15:07

import courses.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=courses.utils.get_path_upload_course_files, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png'], message='Допустимые расширения: .pdf, .doc, .docx, .txt')], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Доп. Документ',
                'verbose_name_plural': 'Доп. Документы',
            },
        ),
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Возрастная категория',
                'verbose_name_plural': 'Возрастные категории',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Ссылка на курс')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тэг')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность курса')),
                ('is_duration_approximately', models.BooleanField(default=False, verbose_name='Длительность курса приблизительна?')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата конца')),
                ('portfolio_text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Портфолио')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('price_all', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая цена')),
                ('without_discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки')),
                ('price_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена в рассрочку')),
                ('time_installment', models.IntegerField(blank=True, null=True, verbose_name='Время рассрочки')),
                ('return_conditions', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Условия возврата')),
                ('has_job_help', models.BooleanField(default=False, verbose_name='Есть помощь с поиском работы?')),
                ('has_job_guarantee', models.BooleanField(default=False, verbose_name='Есть гарантия трудоустройства?')),
                ('provides_diploma', models.BooleanField(default=False, verbose_name='Выдают диплом?')),
                ('diploma_content', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Информация об дипломе')),
                ('has_mentor', models.BooleanField(default=False, verbose_name='Есть ментор?')),
                ('is_webinar', models.BooleanField(default=False, verbose_name='Это вебинар?')),
                ('is_top_sale', models.BooleanField(default=False, verbose_name='Топ продаж?')),
                ('is_wow_effect', models.BooleanField(default=False, verbose_name='Вау эффект?')),
                ('trial_version', models.BooleanField(default=False, verbose_name='Есть пробная версия?')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Курс одобрен?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Курс активен?')),
                ('age_category', models.ManyToManyField(blank=True, to='courses.agecategory', verbose_name='Возрастные категории')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
            },
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=courses.utils.get_path_upload_course_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Допустимые расширения: .jpg, .jpeg, .png, .webp')], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение Курса',
                'verbose_name_plural': 'Изображения Курсов',
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='DirectionsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
                ('error_type', models.CharField(choices=[('Technical Issue', 'Техническая ошибка'), ('Content Error', 'Ошибка в контенте'), ('Payment Error', 'Ошибка в платёжной системе'), ('Other', 'Другая ошибка')], max_length=255, verbose_name='Тип ошибки')),
                ('error_message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('is_read', models.BooleanField(default=False, verbose_name='Ошибка прочитана?')),
            ],
            options={
                'verbose_name': 'Сообщение об ошибке',
                'verbose_name_plural': 'Сообщения об ошибках',
                'db_table': 'error_reports',
                'ordering': ['-created_at'],
                'default_related_name': 'error_reports',
            },
        ),
        migrations.CreateModel(
            name='LearningReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Причина обучения',
                'verbose_name_plural': 'Причины обучения',
            },
        ),
        migrations.CreateModel(
            name='LearningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип Обучения',
                'verbose_name_plural': 'Типы Обучения',
            },
        ),
        migrations.CreateModel(
            name='ShortDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Краткое Описание',
                'verbose_name_plural': 'Краткие Описания',
            },
        ),
        migrations.CreateModel(
            name='ThematicsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.course')),
                ('location', models.JSONField(blank=True, null=True, verbose_name='Локация')),
                ('time_lessons', models.DurationField(blank=True, null=True, verbose_name='Длительность урока')),
                ('grade_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мин. класс')),
                ('grade_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Макс. класс')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Демо?')),
                ('has_parent_control', models.BooleanField(default=False, verbose_name='Есть родительский контроль?')),
                ('has_free_lesson', models.BooleanField(default=False, verbose_name='Есть бесплатные уроки?')),
                ('has_group', models.BooleanField(default=False, verbose_name='Есть групповые занятия?')),
                ('has_record', models.BooleanField(default=False, verbose_name='Есть запись уроков?')),
                ('has_curator', models.BooleanField(default=False, verbose_name='Есть куратор?')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
            bases=('courses.course',),
        ),
    ]
