# Generated by Django 5.1.5 on 2025-03-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='author.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_materials', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_formats',
            field=models.ManyToManyField(blank=True, to='courses.courseformat', verbose_name='Форматы'),
        ),
        migrations.AddField(
            model_name='courseimage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_levels',
            field=models.ManyToManyField(blank=True, to='courses.courselevel', verbose_name='Уровни'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_reasons',
            field=models.ManyToManyField(blank=True, to='courses.learningreasons', verbose_name='Причины изучения'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_types',
            field=models.ManyToManyField(blank=True, to='courses.learningtype', verbose_name='Типы изучения'),
        ),
        migrations.AddField(
            model_name='shortdescription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_descriptions', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='courses_thematics',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.thematicstype', verbose_name='Тематики'),
        ),
        migrations.AddField(
            model_name='school',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='directions', to='courses.directionstype', verbose_name='Направления'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['created_at'], name='error_repor_created_352e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='errorreport',
            index=models.Index(fields=['error_type'], name='error_repor_error_t_4e3b05_idx'),
        ),
    ]
