# Generated by Django 5.1.5 on 2025-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_errorreport_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='agecategory',
            name='translations',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='courseformat',
            name='translations',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='translations',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='directionstype',
            name='translations',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='learningreasons',
            name='translations',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='learningtype',
            name='translations',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Перевод'),
        ),
        migrations.AddField(
            model_name='thematicstype',
            name='translations',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Перевод'),
        ),
    ]
