# Generated by Django 5.1.5 on 2025-04-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_agecategory_translations_courseformat_translations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicstype',
            name='learning_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thematics', to='courses.learningtype', verbose_name='Тип обучения'),
        ),
    ]
