# Generated by Django 5.1.5 on 2025-03-10 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID предмета')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('completed', 'Выполнен'), ('failed', 'Провален'), ('paid', 'Оплачен')], default='processing', max_length=255, verbose_name='Статус')),
                ('payment_type', models.CharField(choices=[('subscription', 'Подписка'), ('course_purchase', 'Покупка Курса'), ('refund', 'Вернуть'), ('other', 'Другое')], default='other', max_length=255, verbose_name='Тип оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата Обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
