# Generated by Django 5.1.5 on 2025-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='yokassa_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа Yokassa'),
        ),
    ]
