# Generated by Django 5.1.5 on 2025-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Подписка'), ('course_purchase', 'Покупка Курса'), ('refund', 'Возврат'), ('other', 'Другое')], default='other', max_length=255, verbose_name='Тип оплаты'),
        ),
    ]
