# Generated by Django 5.1.5 on 2025-03-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Название')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('has_multiple_answers', models.BooleanField(default=True, verbose_name='Имеет несколько ответов?')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('answer_category', models.CharField(blank=True, choices=[('IT', 'IT'), ('CREATIVITY', 'Творчество'), ('SOCIAL_SCIENCE', 'Cоц. Науки'), ('ECONOMICS', 'Экономика'), ('ANALYTICS', 'Аналитика')], default=None, max_length=15, null=True, verbose_name='Категория')),
                ('openness_priority', models.CharField(blank=True, choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default=None, max_length=10, null=True, verbose_name='Приоритет открытости новому')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
