# Generated by Django 5.1.5 on 2025-03-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
            bases=('userauth.customuser',),
        ),
        migrations.CreateModel(
            name='StudentCoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='courses.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='student.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Приобретённый курс',
                'verbose_name_plural': 'Приобретённые курсы',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='bought_courses',
            field=models.ManyToManyField(related_name='buyers', through='student.StudentCoursePurchase', to='courses.course', verbose_name='Купленные курсы'),
        ),
    ]
