# Generated by Django 5.1.5 on 2025-03-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_to_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='parent_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedback', verbose_name='Корневой отзыв'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('feedback.feedback',),
        ),
    ]
