# Generated by Django 5.1.5 on 2025-04-25 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_age_category'),
        ('feedback', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['feedback_rating'], name='feedback_fe_feedbac_96a541_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['is_approved'], name='feedback_fe_is_appr_6b2734_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['feedback_date'], name='feedback_fe_feedbac_cc2134_idx'),
        ),
    ]
